insert into answers values (1, 'I am 27 years old');
insert into answers values (2, 'I am fine');
insert into answers values (3, 'I have 27 years old');
insert into answers values (4, 'on taxi');
insert into answers values (5, 'by taxi');
insert into answers values (6, 'with taxi');
insert into answers values (7, 'for 7 years');
insert into answers values (8, 'at least 7 years');
insert into answers values (9, 'since 7 years');
insert into answers values (10, 'some');
insert into answers values (11, 'a lot');
insert into answers values (12, 'many');
insert into answers values (13, 'is going to');
insert into answers values (14, 'goes to');
insert into answers values (15, 'to going');
insert into answers values (16, 'on Wednesdays');
insert into answers values (17, 'in Wednesdays');
insert into answers values (18, 'at Wednesdays');
insert into answers values (19, 'Would you like?');
insert into answers values (20, 'You would like');
insert into answers values (21, 'Do you?');
insert into answers values (22, 'a white one');
insert into answers values (23, 'a one white');
insert into answers values (24, 'a one');
